### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by atoffano** [Yijia-Xiao/Know2BIO#2]
Hello,

I'm reaching out regarding the full release and safe release dataset, specifically inquiring about the process to access it.

It appears that the Google Forms mentioned in your readme is locked behind an authorization access. I'm assuming that i am not the only user in this case. 
Given this situation, could someone kindly provide guidance on how individuals interested in accessing the dataset should proceed? Are we expected to reconstruct the dataset independently, or is there an alternative method i may have missed for accessing the data?

Any assistance or clarification on this matter would be greatly appreciated.

Thank you!

**Comment by arpelletier** [comment]
Hello.
  Thank you for bringing this to our attention, it is not the intended behavior. We have updated the permissions on the Google Forms. The knowledge graph construction code is provided to construct the dataset on your own with the latest results. The form is intended to grant access to the snapshot of the dataset: either a safe release with all data sources under the release license, or to the full dataset with appropriate licenses.

Link to the form: https://forms.gle/3HdKRtvW7ce9PKpw6
